export interface KanjiChar {
  kanji: string;
  reading: string;  // hiragana reading shown as hint
  meaning: string;  // English meaning — what gets quizzed
}

// Grade 1 kyoiku kanji (80 characters)
export const ALL_KANJI: KanjiChar[] = [
  { kanji: '一', reading: 'いち',     meaning: 'one' },
  { kanji: '二', reading: 'に',       meaning: 'two' },
  { kanji: '三', reading: 'さん',     meaning: 'three' },
  { kanji: '四', reading: 'し',       meaning: 'four' },
  { kanji: '五', reading: 'ご',       meaning: 'five' },
  { kanji: '六', reading: 'ろく',     meaning: 'six' },
  { kanji: '七', reading: 'しち',     meaning: 'seven' },
  { kanji: '八', reading: 'はち',     meaning: 'eight' },
  { kanji: '九', reading: 'きゅう',   meaning: 'nine' },
  { kanji: '十', reading: 'じゅう',   meaning: 'ten' },
  { kanji: '百', reading: 'ひゃく',   meaning: 'hundred' },
  { kanji: '千', reading: 'せん',     meaning: 'thousand' },
  { kanji: '上', reading: 'うえ',     meaning: 'above / up' },
  { kanji: '下', reading: 'した',     meaning: 'below / down' },
  { kanji: '中', reading: 'なか',     meaning: 'middle / inside' },
  { kanji: '大', reading: 'おお',     meaning: 'big / large' },
  { kanji: '小', reading: 'ちいさい', meaning: 'small / little' },
  { kanji: '左', reading: 'ひだり',   meaning: 'left' },
  { kanji: '右', reading: 'みぎ',     meaning: 'right' },
  { kanji: '正', reading: 'ただしい', meaning: 'correct / straight' },
  { kanji: '立', reading: 'たつ',     meaning: 'stand' },
  { kanji: '出', reading: 'でる',     meaning: 'exit / come out' },
  { kanji: '入', reading: 'はいる',   meaning: 'enter / go in' },
  { kanji: '年', reading: 'とし',     meaning: 'year' },
  { kanji: '月', reading: 'つき',     meaning: 'moon / month' },
  { kanji: '日', reading: 'ひ',       meaning: 'sun / day' },
  { kanji: '早', reading: 'はやい',   meaning: 'early / fast' },
  { kanji: '夕', reading: 'ゆう',     meaning: 'evening' },
  { kanji: '休', reading: 'やすみ',   meaning: 'rest' },
  { kanji: '先', reading: 'さき',     meaning: 'ahead / previous' },
  { kanji: '生', reading: 'いきる',   meaning: 'life / live' },
  { kanji: '見', reading: 'みる',     meaning: 'see / look' },
  { kanji: '天', reading: 'てん',     meaning: 'heaven / sky' },
  { kanji: '空', reading: 'そら',     meaning: 'sky / empty' },
  { kanji: '山', reading: 'やま',     meaning: 'mountain' },
  { kanji: '川', reading: 'かわ',     meaning: 'river' },
  { kanji: '田', reading: 'た',       meaning: 'rice field' },
  { kanji: '土', reading: 'つち',     meaning: 'soil / earth' },
  { kanji: '石', reading: 'いし',     meaning: 'stone / rock' },
  { kanji: '火', reading: 'ひ',       meaning: 'fire' },
  { kanji: '水', reading: 'みず',     meaning: 'water' },
  { kanji: '木', reading: 'き',       meaning: 'tree / wood' },
  { kanji: '金', reading: 'きん',     meaning: 'gold / money' },
  { kanji: '花', reading: 'はな',     meaning: 'flower' },
  { kanji: '草', reading: 'くさ',     meaning: 'grass' },
  { kanji: '林', reading: 'はやし',   meaning: 'grove / woods' },
  { kanji: '森', reading: 'もり',     meaning: 'forest' },
  { kanji: '竹', reading: 'たけ',     meaning: 'bamboo' },
  { kanji: '虫', reading: 'むし',     meaning: 'insect / bug' },
  { kanji: '犬', reading: 'いぬ',     meaning: 'dog' },
  { kanji: '貝', reading: 'かい',     meaning: 'shell' },
  { kanji: '雨', reading: 'あめ',     meaning: 'rain' },
  { kanji: '円', reading: 'えん',     meaning: 'circle / yen' },
  { kanji: '王', reading: 'おう',     meaning: 'king' },
  { kanji: '音', reading: 'おと',     meaning: 'sound' },
  { kanji: '気', reading: 'き',       meaning: 'spirit / energy' },
  { kanji: '玉', reading: 'たま',     meaning: 'ball / jewel' },
  { kanji: '車', reading: 'くるま',   meaning: 'car / wheel' },
  { kanji: '人', reading: 'ひと',     meaning: 'person' },
  { kanji: '女', reading: 'おんな',   meaning: 'woman' },
  { kanji: '男', reading: 'おとこ',   meaning: 'man' },
  { kanji: '子', reading: 'こ',       meaning: 'child' },
  { kanji: '学', reading: 'まなぶ',   meaning: 'study / learn' },
  { kanji: '校', reading: 'こう',     meaning: 'school' },
  { kanji: '口', reading: 'くち',     meaning: 'mouth' },
  { kanji: '手', reading: 'て',       meaning: 'hand' },
  { kanji: '足', reading: 'あし',     meaning: 'foot / leg' },
  { kanji: '目', reading: 'め',       meaning: 'eye' },
  { kanji: '耳', reading: 'みみ',     meaning: 'ear' },
  { kanji: '力', reading: 'ちから',   meaning: 'power / strength' },
  { kanji: '名', reading: 'な',       meaning: 'name' },
  { kanji: '字', reading: 'じ',       meaning: 'character / letter' },
  { kanji: '文', reading: 'ふみ',     meaning: 'writing / sentence' },
  { kanji: '本', reading: 'ほん',     meaning: 'book / origin' },
  { kanji: '白', reading: 'しろ',     meaning: 'white' },
  { kanji: '赤', reading: 'あか',     meaning: 'red' },
  { kanji: '青', reading: 'あお',     meaning: 'blue' },
  { kanji: '糸', reading: 'いと',     meaning: 'thread / string' },
  { kanji: '町', reading: 'まち',     meaning: 'town' },
  { kanji: '村', reading: 'むら',     meaning: 'village' },
];
